let productDB = [
  {
    id: 1,
    title: "Headphone",
    size: "large",
    imgurl: `imgs/head.jfif`,
    qty: 1,
    isme: "N",
    liked: false,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid non ea dolores",
  },
  {
    id: 2,
    title: "Labtop",
    size: "small",
    imgurl: `imgs/Lab.jfif`,
    qty: 1,
    isme: "N",
    liked: false,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid non ea dolores",
  },
  {
    id: 3,
    title: "Glasses",
    size: "medium",
    imgurl: `imgs/sun.jfif`,
    qty: 1,
    isme: "N",
    liked: false,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid non ea dolores",
  },
  {
    id: 8,
    title: "Watch",
    size: "small",
    imgurl: `imgs/Wach6.jfif`,
    qty: 1,
    isme: "N",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid non ea dolores",
  },
  {
    id: 4,
    title: "Watch",
    size: "small",
    imgurl: `imgs/Watch.jfif`,
    qty: 1,
    isme: "N",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid non ea dolores",
  },
  {
    id: 5,
    title: "Watch",
    size: "large",
    imgurl: `imgs/Wath2.jfif`,
    qty: 1,
    isme: "N",
    liked: false,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid non ea dolores",
  },
  {
    id: 6,
    title: "Watch",
    size: "small",
    imgurl: `imgs/Watch3.jfif`,
    qty: 1,
    isme: "N",
    liked: false,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid non ea dolores",
  },
  {
    id: 7,
    title: "Watch",
    size: "medium",
    imgurl: `imgs/Wach5.jfif`,
    qty: 1,
    isme: "N",
    liked: false,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid non ea dolores",
  },
  {
    id: 14,
    title: "Choose",
    size: "large",
    imgurl: `imgs/Choose.jfif`,
    qty: 1,
    isme: "N",
    liked: false,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid non ea dolores",
  },

  {
    id: 9,
    title: "Watch",
    size: "small",
    imgurl: `imgs/Wach7.jfif`,
    qty: 1,
    isme: "N",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid non ea dolores",
  },

  {
    id: 10,
    title: "Choose",
    size: "small",
    imgurl: `imgs/Choose2.jfif`,
    qty: 1,
    isme: "N",
    liked: false,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid non ea dolores",
  },
  {
    id: 11,
    title: "Choose",
    size: "medium",
    imgurl: `imgs/Choose3.jfif`,
    qty: 1,
    isme: "N",
    liked: false,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid non ea dolores",
  },
  {
    id: 12,
    title: "Watch",
    size: "small",
    imgurl: `imgs/Wach6.jfif`,
    qty: 1,
    isme: "N",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid non ea dolores",
  },
  {
    id: 17,
    title: "Watch",
    size: "small",
    imgurl: `imgs/Wach4.jfif`,
    qty: 1,
    isme: "N",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid non ea dolores",
  },
  {
    id: 13,
    title: "Choose",
    size: "small",
    imgurl: `imgs/Choose5.jfif`,
    qty: 1,
    isme: "N",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid non ea dolores",
  },
];
// Choose

// localStorage.setItem("products", JSON.stringify(productDB));
